---
name: Upgrade NPM dependencies

# NOTE: This workflow requires the addition of two secrets to your repository,
# `APP_ID` and `APP_PRIVATE_KEY` which must be the ID and a private key for a
# GitHub app with permission to read/write contents and pull requests.

on:
  schedule:
    # Run daily at 12:15 UTC (08:15 EDT/07:15 EST)
    - cron: "15 12 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  npm:
    name: Fetch and apply updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          # Set this to the required version of Node for your project
          node-version: "lts/*"
          cache: npm

      - name: Install latest npm and and npm-check-updates
        run: npm install -g npm@latest npm-check-updates@latest

      # This section may need additional modifications to properly suite your
      # project. For example, you may need to filter specific dependencies for
      # `ncu` or perform additional steps to properly install dependencies in
      # all packages in a monorepo configuration or you may be using yarn
      # instead of npm on your project
      - name: Update project dependencies
        run: |-
          ncu --deep --upgrade
      - name: Install updated dependencies
        run: |-
          npm install
          npm update

      - name: Login as the automation app
        id: generate-token
        uses: tibdex/github-app-token@586e1a624db6a5a4ac2c53daeeded60c5e3d50fe
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create update pull request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update NPM dependencies
          title: Update NPM dependencies
          body: >-
            This was generated by the "${{ github.workflow }}" workflow, primarily
            by running `node-check-updates` and `npm install`.
          branch: automation/update-npm-dependencies
          delete-branch: true
          base: $default-branch
          committer: Easy Dynamics Automation <noreply@easydynamics.com>
          author: Easy Dynamics Automation <noreply@easydynamics.com>
          token: "${{ steps.generate-token.outputs.token }}"
